import enum

# https://team.sa-mp.com/wiki/Skins_All.html
# https://wiki.multitheftauto.com/wiki/All_Skins_Page
# https://www.open.mp/docs/scripting/resources/skins

MAX_SKIN_ID = 311

class Skin:
    def __init__(self, id, model, male, description):
        self.id = id
        self.model = model
        self.male = bool(male)
        self.description = description

skins = [
#    id    model      male  description
#    |      |          |    |
Skin(0   , 'cj'      , 1 , 'Carl "CJ" Johnson (Main Character)'),
Skin(1   , 'truth'   , 1 , 'The Truth'),
Skin(2   , 'maccer'  , 1 , 'Maccer'),
Skin(3   , 'andre'   , 1 , 'Andre'),
Skin(4   , 'bbthin'  , 1 , 'Barry "Big Bear" Thorne [Thin]'),
Skin(5   , 'bb'      , 1 , 'Barry "Big Bear" Thorne [Big]'),
Skin(6   , 'emmet'   , 1 , 'Emmet'),
Skin(7   , 'male01'  , 1 , 'Taxi Driver/Train Driver'),
Skin(8   , 'janitor' , 1 , 'Janitor'),
Skin(9   , 'bfori'   , 0 , 'Normal Ped'),
Skin(10  , 'bfost'   , 0 , 'Old Woman'),
Skin(11  , 'vbfycrp' , 0 , 'Casino croupier'),
Skin(12  , 'bfyri'   , 0 , 'Rich Woman'),
Skin(13  , 'bfyst'   , 0 , 'Street Girl'),
Skin(14  , 'bmori'   , 1 , 'Normal Ped'),
Skin(15  , 'bmost'   , 1 , 'Mr.Whittaker (RS Haul Owner)'),
Skin(16  , 'bmyap'   , 1 , 'Airport Ground Worker'),
Skin(17  , 'bmybu'   , 1 , 'Businessman'),
Skin(18  , 'bmybe'   , 1 , 'Beach Visitor'),
Skin(19  , 'bmydj'   , 1 , 'DJ'),
Skin(20  , 'bmyri'   , 1 , 'Rich Guy (Madd Dogg\'s Manager)'),
Skin(21  , 'bmycr'   , 1 , 'Normal Ped'),
Skin(22  , 'bmyst'   , 1 , 'Normal Ped'),
Skin(23  , 'wmybmx'  , 1 , 'BMXer'),
Skin(24  , 'wbdyg1'  , 1 , 'Madd Dogg Bodyguard'),
Skin(25  , 'wbdyg2'  , 1 , 'Madd Dogg Bodyguard'),
Skin(26  , 'wmybp'   , 1 , 'Backpacker'),
Skin(27  , 'wmycon'  , 1 , 'Construction Worker'),
Skin(28  , 'bmydrug' , 1 , 'Drug Dealer'),
Skin(29  , 'wmydrug' , 1 , 'Drug Dealer'),
Skin(30  , 'hmydrug' , 1 , 'Drug Dealer'),
Skin(31  , 'dwfolc'  , 0 , 'Farm-Town inhabitant'),
Skin(32  , 'dwmolc1' , 1 , 'Farm-Town inhabitant'),
Skin(33  , 'dwmolc2' , 1 , 'Farm-Town inhabitant'),
Skin(34  , 'dwmylc1' , 1 , 'Farm-Town inhabitant'),
Skin(35  , 'hmogar'  , 1 , 'Gardener'),
Skin(36  , 'wmygol1' , 1 , 'Golfer'),
Skin(37  , 'wmygol2' , 1 , 'Golfer'),
Skin(38  , 'hfori'   , 0 , 'Normal Ped'),
Skin(39  , 'hfost'   , 0 , 'Normal Ped'),
Skin(40  , 'hfyri'   , 0 , 'Normal Ped'),
Skin(41  , 'hfyst'   , 0 , 'Normal Ped'),
Skin(42  , 'jethro'  , 1 , 'Jethro'),
Skin(43  , 'hmori'   , 1 , 'Normal Ped'),
Skin(44  , 'hmost'   , 1 , 'Normal Ped'),
Skin(45  , 'hmybe'   , 1 , 'Beach Visitor'),
Skin(46  , 'hmyri'   , 1 , 'Normal Ped'),
Skin(47  , 'hmycr'   , 1 , 'Normal Ped'),
Skin(48  , 'hmyst'   , 1 , 'Normal Ped'),
Skin(49  , 'omokung' , 1 , 'Snakehead (Da Nang)'),
Skin(50  , 'wmymech' , 1 , 'Mechanic'),
Skin(51  , 'bmymoun' , 1 , 'Mountain Biker'),
Skin(52  , 'wmymoun' , 1 , 'Mountain Biker'),
Skin(53  , 'ofori'   , 0 , 'Unknown'),
Skin(54  , 'ofost'   , 0 , 'Normal Ped'),
Skin(55  , 'ofyri'   , 0 , 'Normal Ped'),
Skin(56  , 'ofyst'   , 0 , 'Normal Ped'),
Skin(57  , 'omori'   , 1 , 'Oriental Ped'),
Skin(58  , 'omost'   , 1 , 'Oriental Ped'),
Skin(59  , 'omyri'   , 1 , 'Normal Ped'),
Skin(60  , 'omyst'   , 1 , 'Normal Ped'),
Skin(61  , 'wmyplt'  , 1 , 'Pilot'),
Skin(62  , 'wmopj'   , 1 , 'Colonel Fuhrberger'),
Skin(63  , 'bfypro'  , 0 , 'Prostitute'),
Skin(64  , 'hfypro'  , 0 , 'Prostitute'),
Skin(65  , 'kendl'   , 0 , 'Kendl Johnson'),
Skin(66  , 'bmypol1' , 1 , 'Pool Player'),
Skin(67  , 'bmypol2' , 1 , 'Pool Player'),
Skin(68  , 'wmoprea' , 1 , 'Priest/Preacher'),
Skin(69  , 'sbfyst'  , 0 , 'Normal Ped'),
Skin(70  , 'wmosci'  , 1 , 'Scientist'),
Skin(71  , 'wmysgrd' , 1 , 'Security Guard'),
Skin(72  , 'swmyhp1' , 1 , 'Hippy'),
Skin(73  , 'swmyhp2' , 1 , 'Hippy'),
Skin(75  , 'swfopro' , 0 , 'Prostitute'),
Skin(76  , 'wfystew' , 0 , 'Stewardess'),
Skin(77  , 'swmotr1' , 0 , 'Homeless'),
Skin(78  , 'wmotr1'  , 1 , 'Homeless'),
Skin(79  , 'bmotr1'  , 1 , 'Homeless'),
Skin(80  , 'vbmybox' , 1 , 'Boxer'),
Skin(81  , 'vwmybox' , 1 , 'Boxer'),
Skin(82  , 'vhmyelv' , 1 , 'Black Elvis'),
Skin(83  , 'vbmyelv' , 1 , 'White Elvis'),
Skin(84  , 'vimyelv' , 1 , 'Blue Elvis'),
Skin(85  , 'vwfypro' , 0 , 'Prostitute'),
Skin(86  , 'ryder3'  , 1 , 'Ryder with robbery mask'),
Skin(87  , 'vwfyst1' , 0 , 'Stripper'),
Skin(88  , 'wfori'   , 0 , 'Normal Ped'),
Skin(89  , 'wfost'   , 0 , 'Normal Ped'),
Skin(90  , 'wfyjg'   , 0 , 'Jogger'),
Skin(91  , 'wfyri'   , 0 , 'Rich Woman'),
Skin(92  , 'wfyro'   , 0 , 'Rollerskater'),
Skin(93  , 'wfyst'   , 0 , 'Normal Ped'),
Skin(94  , 'wmori'   , 1 , 'Normal Ped'),
Skin(95  , 'wmost'   , 1 , 'Normal Ped, Works at or owns Dillimore Gas Station'),
Skin(96  , 'wmyjg'   , 1 , 'Jogger'),
Skin(97  , 'wmylg'   , 1 , 'Lifeguard'),
Skin(98  , 'wmyri'   , 1 , 'Normal Ped'),
Skin(99  , 'wmyro'   , 1 , 'Rollerskater'),
Skin(100 , 'wmycr'   , 1 , 'Biker'),
Skin(101 , 'wmyst'   , 1 , 'Normal Ped'),
Skin(102 , 'ballas1' , 1 , 'Balla'),
Skin(103 , 'ballas2' , 1 , 'Balla'),
Skin(104 , 'ballas3' , 1 , 'Balla'),
Skin(105 , 'fam1'    , 1 , 'Grove Street Families'),
Skin(106 , 'fam2'    , 1 , 'Grove Street Families'),
Skin(107 , 'fam3'    , 1 , 'Grove Street Families'),
Skin(108 , 'lsv1'    , 1 , 'Los Santos Vagos'),
Skin(109 , 'lsv2'    , 1 , 'Los Santos Vagos'),
Skin(110 , 'lsv3'    , 1 , 'Los Santos Vagos'),
Skin(111 , 'maffa'   , 1 , 'The Russian Mafia'),
Skin(112 , 'maffb'   , 1 , 'The Russian Mafia'),
Skin(113 , 'mafboss' , 1 , 'The Russian Mafia'),
Skin(114 , 'vla1'    , 1 , 'Varios Los Aztecas'),
Skin(115 , 'vla2'    , 1 , 'Varios Los Aztecas'),
Skin(116 , 'vla3'    , 1 , 'Varios Los Aztecas'),
Skin(117 , 'triada'  , 1 , 'Triad'),
Skin(118 , 'triadb'  , 1 , 'Triad'),
Skin(119 , 'sindaco' , 1 , 'Johhny Sindacco'),
Skin(120 , 'triboss' , 1 , 'Triad Boss'),
Skin(121 , 'dnb1'    , 1 , 'Da Nang Boy'),
Skin(122 , 'dnb2'    , 1 , 'Da Nang Boy'),
Skin(123 , 'dnb3'    , 1 , 'Da Nang Boy'),
Skin(124 , 'vmaff1'  , 1 , 'The Mafia'),
Skin(125 , 'vmaff2'  , 1 , 'The Mafia'),
Skin(126 , 'vmaff3'  , 1 , 'The Mafia'),
Skin(127 , 'vmaff4'  , 1 , 'The Mafia'),
Skin(128 , 'dnmylc'  , 1 , 'Farm Inhabitant'),
Skin(129 , 'dnfolc1' , 0 , 'Farm Inhabitant'),
Skin(130 , 'dnfolc2' , 0 , 'Farm Inhabitant'),
Skin(131 , 'dnfylc'  , 0 , 'Farm Inhabitant'),
Skin(132 , 'dnmolc1' , 1 , 'Farm Inhabitant'),
Skin(133 , 'dnmolc2' , 1 , 'Farm Inhabitant'),
Skin(134 , 'sbmotr2' , 1 , 'Homeless'),
Skin(135 , 'swmotr2' , 1 , 'Homeless'),
Skin(136 , 'sbmytr3' , 1 , 'Normal Ped'),
Skin(137 , 'swmotr3' , 1 , 'Homeless'),
Skin(138 , 'wfybe'   , 0 , 'Beach Visitor'),
Skin(139 , 'bfybe'   , 0 , 'Beach Visitor'),
Skin(140 , 'hfybe'   , 0 , 'Beach Visitor'),
Skin(141 , 'sofybu'  , 0 , 'Businesswoman'),
Skin(142 , 'sbmyst'  , 1 , 'Taxi Driver'),
Skin(143 , 'sbmycr'  , 1 , 'Crack Maker'),
Skin(144 , 'bmycg'   , 1 , 'Crack Maker'),
Skin(145 , 'wfycrk'  , 0 , 'Crack Maker'),
Skin(146 , 'hmycm'   , 1 , 'Crack Maker'),
Skin(147 , 'wmybu'   , 1 , 'Businessman'),
Skin(148 , 'bfybu'   , 0 , 'Businesswoman'),
Skin(149 , 'smokev'  , 1 , 'Big Smoke Armored'),
Skin(150 , 'wfybu'   , 0 , 'Businesswoman'),
Skin(151 , 'dwfylc1' , 0 , 'Normal Ped'),
Skin(152 , 'wfypro'  , 0 , 'Prostitute'),
Skin(153 , 'wmyconb' , 1 , 'Construction Worker'),
Skin(154 , 'wmybe'   , 1 , 'Beach Visitor'),
Skin(155 , 'wmypizz' , 1 , 'Well Stacked Pizza Worker'),
Skin(156 , 'bmobar'  , 1 , 'Barber'),
Skin(157 , 'cwfyhb'  , 0 , 'Hillbilly'),
Skin(158 , 'cwmofr'  , 1 , 'Farmer'),
Skin(159 , 'cwmohb1' , 1 , 'Hillbilly'),
Skin(160 , 'cwmohb2' , 1 , 'Hillbilly'),
Skin(161 , 'cwmyfr'  , 1 , 'Farmer'),
Skin(162 , 'cwmyhb1' , 1 , 'Hillbilly'),
Skin(163 , 'bmyboun' , 1 , 'Black Bouncer'),
Skin(164 , 'wmyboun' , 1 , 'White Bouncer'),
Skin(165 , 'wmomib'  , 1 , 'White MIB agent'),
Skin(166 , 'bmymib'  , 1 , 'Black MIB agent'),
Skin(167 , 'wmybell' , 1 , 'Cluckin\' Bell Worker'),
Skin(168 , 'bmochil' , 1 , 'Hotdog/Chilli Dog Vendor'),
Skin(169 , 'sofyri'  , 0 , 'Normal Ped'),
Skin(170 , 'somyst'  , 1 , 'Normal Ped'),
Skin(171 , 'vwmybjd' , 1 , 'Blackjack Dealer'),
Skin(172 , 'vwfycrp' , 0 , 'Casino croupier'),
Skin(173 , 'sfr1'    , 1 , 'San Fierro Rifa'),
Skin(174 , 'sfr2'    , 1 , 'San Fierro Rifa'),
Skin(175 , 'sfr3'    , 1 , 'San Fierro Rifa'),
Skin(176 , 'bmybar'  , 1 , 'Barber'),
Skin(177 , 'wmybar'  , 1 , 'Barber'),
Skin(178 , 'wfysex'  , 0 , 'Whore'),
Skin(179 , 'wmyammo' , 1 , 'Ammunation Salesman'),
Skin(180 , 'bmytatt' , 1 , 'Tattoo Artist'),
Skin(181 , 'vwmycr'  , 1 , 'Punk'),
Skin(182 , 'vbmocd'  , 1 , 'Cab Driver'),
Skin(183 , 'vbmycr'  , 1 , 'Normal Ped'),
Skin(184 , 'vhmycr'  , 1 , 'Normal Ped'),
Skin(185 , 'sbmyri'  , 1 , 'Normal Ped'),
Skin(186 , 'somyri'  , 1 , 'Normal Ped'),
Skin(187 , 'somybu'  , 1 , 'Businessman'),
Skin(188 , 'swmyst'  , 1 , 'Normal Ped'),
Skin(189 , 'wmyva'   , 1 , 'Valet'),
Skin(190 , 'copgrl3' , 0 , 'Barbara Schternvart'),
Skin(191 , 'gungrl3' , 0 , 'Helena Wankstein'),
Skin(192 , 'mecgrl3' , 0 , 'Michelle Cannes'),
Skin(193 , 'nurgrl3' , 0 , 'Katie Zhan'),
Skin(194 , 'crogrl3' , 0 , 'Millie Perkins'),
Skin(195 , 'gangrl3' , 0 , 'Denise Robinson'),
Skin(196 , 'cwfofr'  , 0 , 'Farm-Town inhabitant'),
Skin(197 , 'cwfohb'  , 0 , 'Hillbilly'),
Skin(198 , 'cwfyfr1' , 0 , 'Farm-Town inhabitant'),
Skin(199 , 'cwfyfr2' , 0 , 'Farm-Town inhabitant'),
Skin(200 , 'cwmyhb2' , 1 , 'Hillbilly'),
Skin(201 , 'dwfylc2' , 0 , 'Farmer'),
Skin(202 , 'dwmylc2' , 1 , 'Farmer'),
Skin(203 , 'omykara' , 1 , 'Karate Teacher'),
Skin(204 , 'wmykara' , 1 , 'Karate Teacher'),
Skin(205 , 'wfyburg' , 0 , 'Burger Shot Cashier'),
Skin(206 , 'vwmycd'  , 1 , 'Cab Driver'),
Skin(207 , 'vhfypro' , 0 , 'Prostitute'),
Skin(208 , 'suzie'   , 1 , 'Su Xi Mu (Suzie)'),
Skin(209 , 'omonood' , 1 , 'Oriental Noodle stand vendor'),
Skin(210 , 'omoboat' , 1 , 'Oriental Boating School Instructor'),
Skin(211 , 'wfyclot' , 0 , 'Clothes shop staff'),
Skin(212 , 'vwmotr1' , 1 , 'Homeless'),
Skin(213 , 'vwmotr2' , 1 , 'Weird old man'),
Skin(214 , 'vwfywai' , 0 , 'Waitress (Maria Latore)'),
Skin(215 , 'sbfori'  , 0 , 'Normal Ped'),
Skin(216 , 'swfyri'  , 0 , 'Normal Ped'),
Skin(217 , 'wmyclot' , 1 , 'Clothes shop staff'),
Skin(218 , 'sbfost'  , 0 , 'Normal Ped'),
Skin(219 , 'sbfyri'  , 0 , 'Rich Woman'),
Skin(220 , 'sbmocd'  , 1 , 'Cab Driver'),
Skin(221 , 'sbmori'  , 1 , 'Normal Ped'),
Skin(222 , 'sbmost'  , 1 , 'Normal Ped'),
Skin(223 , 'shmycr'  , 1 , 'Normal Ped'),
Skin(224 , 'sofori'  , 0 , 'Normal Ped'),
Skin(225 , 'sofost'  , 0 , 'Normal Ped'),
Skin(226 , 'sofyst'  , 0 , 'Normal Ped'),
Skin(227 , 'somobu'  , 1 , 'Oriental Businessman'),
Skin(228 , 'somori'  , 1 , 'Oriental Ped'),
Skin(229 , 'somost'  , 1 , 'Oriental Ped'),
Skin(230 , 'swmotr5' , 1 , 'Homeless'),
Skin(231 , 'swfori'  , 0 , 'Normal Ped'),
Skin(232 , 'swfost'  , 0 , 'Normal Ped'),
Skin(233 , 'swfyst'  , 0 , 'Normal Ped'),
Skin(234 , 'swmocd'  , 1 , 'Cab Driver'),
Skin(235 , 'swmori'  , 1 , 'Normal Ped'),
Skin(236 , 'swmost'  , 1 , 'Normal Ped'),
Skin(237 , 'shfypro' , 0 , 'Prostitute'),
Skin(238 , 'sbfypro' , 0 , 'Prostitute'),
Skin(239 , 'swmotr4' , 1 , 'Homeless'),
Skin(240 , 'swmyri'  , 1 , 'The D.A'),
Skin(241 , 'smyst'   , 1 , 'Afro-American'),
Skin(242 , 'smyst2'  , 1 , 'Mexican'),
Skin(243 , 'sfypro'  , 0 , 'Prostitute'),
Skin(244 , 'vbfyst2' , 0 , 'Stripper'),
Skin(245 , 'vbfypro' , 0 , 'Prostitute'),
Skin(246 , 'vhfyst3' , 0 , 'Stripper'),
Skin(247 , 'bikera'  , 1 , 'Biker'),
Skin(248 , 'bikerb'  , 1 , 'Biker'),
Skin(249 , 'bmypimp' , 1 , 'Pimp'),
Skin(250 , 'swmycr'  , 1 , 'Normal Ped'),
Skin(251 , 'wfylg'   , 0 , 'Lifeguard'),
Skin(252 , 'wmyva2'  , 1 , 'Naked Valet'),
Skin(253 , 'bmosec'  , 1 , 'Bus Driver'),
Skin(254 , 'bikdrug' , 1 , 'Biker Drug Dealer'),
Skin(255 , 'wmych'   , 1 , 'Chauffeur (Limo Driver)'),
Skin(256 , 'sbfystr' , 0 , 'Stripper'),
Skin(257 , 'swfystr' , 0 , 'Stripper'),
Skin(258 , 'heck1'   , 1 , 'Heckler'),
Skin(259 , 'heck2'   , 1 , 'Heckler'),
Skin(260 , 'bmycon'  , 1 , 'Construction Worker'),
Skin(261 , 'wmycd1'  , 1 , 'Cab driver'),
Skin(262 , 'bmocd'   , 1 , 'Cab driver'),
Skin(263 , 'vwfywa2' , 0 , 'Normal Ped'),
Skin(264 , 'wmoice'  , 1 , 'Clown (Ice-cream Van Driver)'),
Skin(265 , 'tenpen'  , 1 , 'Officer Frank Tenpenny (Corrupt Cop)'),
Skin(266 , 'pulaski' , 1 , 'Officer Eddie Pulaski (Corrupt Cop)'),
Skin(267 , 'hern'    , 1 , 'Officer Jimmy Hernandez'),
Skin(268 , 'dwayne'  , 1 , 'Dwaine/Dwayne'),
Skin(269 , 'smoke'   , 1 , 'Melvin "Big Smoke" Harris (Mission)'),
Skin(270 , 'sweet'   , 1 , 'Sean \'Sweet\' Johnson'),
Skin(271 , 'ryder'   , 1 , 'Lance \'Ryder\' Wilson'),
Skin(272 , 'forelli' , 1 , 'Mafia Boss'),
Skin(273 , 'tbone'   , 1 , 'T-Bone Mendez'),
Skin(274 , 'laemt1'  , 1 , 'Paramedic (Emergency Medical Technician)'),
Skin(275 , 'lvemt1'  , 1 , 'Paramedic (Emergency Medical Technician)'),
Skin(276 , 'sfemt1'  , 1 , 'Paramedic (Emergency Medical Technician)'),
Skin(277 , 'lafd1'   , 1 , 'Firefighter'),
Skin(278 , 'lvfd1'   , 1 , 'Firefighter'),
Skin(279 , 'sffd1'   , 1 , 'Firefighter'),
Skin(280 , 'lapd1'   , 1 , 'Los Santos Police Officer'),
Skin(281 , 'sfpd1'   , 1 , 'San Fierro Police Officer'),
Skin(282 , 'lvpd1'   , 1 , 'Las Venturas Police Officer'),
Skin(283 , 'csher'   , 1 , 'County Sheriff'),
Skin(284 , 'lapdm1'  , 1 , 'LSPD Motorbike Cop'),
Skin(285 , 'swat'    , 1 , 'S.W.A.T Special Forces'),
Skin(286 , 'fbi'     , 1 , 'Federal Agent'),
Skin(287 , 'army'    , 1 , 'San Andreas Army'),
Skin(288 , 'dsher'   , 1 , 'Desert Sheriff'),
Skin(289 , 'zero'    , 1 , 'Zero'),
Skin(290 , 'rose'    , 1 , 'Ken Rosenberg'),
Skin(291 , 'paul'    , 1 , 'Kent Paul'),
Skin(292 , 'cesar'   , 1 , 'Cesar Vialpando'),
Skin(293 , 'ogloc'   , 1 , 'Jeffery "OG Loc" Martin/Cross'),
Skin(294 , 'wuzimu'  , 1 , 'Wu Zi Mu (Woozie)'),
Skin(295 , 'torino'  , 1 , 'Michael Toreno'),
Skin(296 , 'jizzy'   , 1 , 'Jizzy B.'),
Skin(297 , 'maddogg' , 1 , 'Madd Dogg'),
Skin(298 , 'cat'     , 0 , 'Catalina'),
Skin(299 , 'claude'  , 1 , 'Claude Speed'),
Skin(300 , 'lapdna'  , 1 , 'Los Santos Police Officer (Without gun holster)'),
Skin(301 , 'sfpdna'  , 1 , 'San Fierro Police Officer (Without gun holster)'),
Skin(302 , 'lvpdna'  , 1 , 'Las Venturas Police Officer (Without gun holster)'),
Skin(303 , 'lapdpc'  , 1 , 'Los Santos Police Officer (Without uniform)'),
Skin(304 , 'lapdpd'  , 1 , 'Los Santos Police Officer (Without uniform)'),
Skin(305 , 'lvpdpc'  , 1 , 'Las Venturas Police Officer (Without uniform)'),
Skin(306 , 'wfyclpd' , 0 , 'Los Santos Police Officer'),
Skin(307 , 'vbfycpd' , 0 , 'San Fierro Police Officer'),
Skin(308 , 'wfyclem' , 0 , 'San Fierro Paramedic (Emergency Medical Technician)'),
Skin(309 , 'wfycllv' , 0 , 'Las Venturas Police Officer'),
Skin(310 , 'csherna' , 1 , 'Country Sheriff (Without hat)'),
Skin(311 , 'dsherna' , 1 , 'Desert Sheriff (Without hat)'),
]

# enum makes code more readable
# e.g. SKIN.CJ returns cj skin id(0)
SKIN = enum.IntEnum('SKIN', {skins.model.upper():skins.id for skins in skins})
