import enum

# https://sampwiki.blast.hk/wiki/Vehicles:All
# https://team.sa-mp.com/wiki/Category_Vehicle.html
# https://www.open.mp/docs/scripting/resources/vehicleid
# https://wiki.multitheftauto.com/wiki/Vehicle_IDs

MIN_VEHICLE_MODEL_ID = 400
MAX_VEHICLE_MODEL_ID = 611

class VehicleModel:
    def __init__(self, model_id, name, model, seat_count, category, mod_shop):
        self.model_id = model_id
        self.name = name
        self.model = model
        self.seat_count = seat_count
        self.category = category
        self.mod_shop = mod_shop

# table indexable by model id
# e.g. vehicle_models[408] returns VehicleModel(408, 'Trashmaster', 'trash', 2, 'Industrial', 'None')
# e.g. vehicle_models[VEHICLE.RHINO] returns VehicleModel(432, 'Rhino', 'rhino', 1, 'Public Service', 'None'),
vehicle_models = [None] * 400 + [
#        model_id    name                model  seat_count  category        mod_shop
#             |       |                    |          |      |                 |
VehicleModel(400 , 'Landstalker'       , 'landstal' , 4 , 'Off Road'        , 'Transfender'),
VehicleModel(401 , 'Bravura'           , 'bravura'  , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(402 , 'Buffalo'           , 'buffalo'  , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(403 , 'Linerunner'        , 'linerun'  , 2 , 'Industrial'      , 'None'),
VehicleModel(404 , 'Perennial'         , 'peren'    , 4 , 'Station Wagons'  , 'Transfender'),
VehicleModel(405 , 'Sentinel'          , 'sentinel' , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(406 , 'Dumper'            , 'dumper'   , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(407 , 'Firetruck'         , 'firetruk' , 2 , 'Public Service'  , 'None'),
VehicleModel(408 , 'Trashmaster'       , 'trash'    , 2 , 'Industrial'      , 'None'),
VehicleModel(409 , 'Stretch'           , 'stretch'  , 4 , 'Unique Vehicles' , 'Transfender'),
VehicleModel(410 , 'Manana'            , 'manana'   , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(411 , 'Infernus'          , 'infernus' , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(412 , 'Voodoo'            , 'voodoo'   , 2 , 'Lowriders'       , 'Loco Low Co'),
VehicleModel(413 , 'Pony'              , 'pony'     , 4 , 'Industrial'      , 'None'),
VehicleModel(414 , 'Mule'              , 'mule'     , 2 , 'Industrial'      , 'None'),
VehicleModel(415 , 'Cheetah'           , 'cheetah'  , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(416 , 'Ambulance'         , 'ambulan'  , 4 , 'Public Service'  , 'None'),
VehicleModel(417 , 'Leviathan'         , 'leviathn' , 2 , 'Helicopters'     , 'None'),
VehicleModel(418 , 'Moonbeam'          , 'moonbeam' , 4 , 'Station Wagons'  , 'Transfender'),
VehicleModel(419 , 'Esperanto'         , 'esperant' , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(420 , 'Taxi'              , 'taxi'     , 4 , 'Public Service'  , 'Transfender'),
VehicleModel(421 , 'Washington'        , 'washing'  , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(422 , 'Bobcat'            , 'bobcat'   , 2 , 'Industrial'      , 'Transfender'),
VehicleModel(423 , 'Mr. Whoopee'       , 'mrwhoop'  , 2 , 'Unique Vehicles' , 'None'),
VehicleModel(424 , 'BF Injection'      , 'bfinject' , 2 , 'Off Road'        , 'None'),
VehicleModel(425 , 'Hunter'            , 'hunter'   , 1 , 'Helicopters'     , 'None'),
VehicleModel(426 , 'Premier'           , 'premier'  , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(427 , 'Enforcer'          , 'enforcer' , 4 , 'Public Service'  , 'None'),
VehicleModel(428 , 'Securicar'         , 'securica' , 4 , 'Unique Vehicles' , 'None'),
VehicleModel(429 , 'Banshee'           , 'banshee'  , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(430 , 'Predator'          , 'predator' , 1 , 'Boats'           , 'None'),
VehicleModel(431 , 'Bus'               , 'bus'      , 9 , 'Public Service'  , 'None'),
VehicleModel(432 , 'Rhino'             , 'rhino'    , 1 , 'Public Service'  , 'None'),
VehicleModel(433 , 'Barracks'          , 'barracks' , 2 , 'Public Service'  , 'None'),
VehicleModel(434 , 'Hotknife'          , 'hotknife' , 2 , 'Unique Vehicles' , 'None'),
VehicleModel(435 , 'Trailer'           , 'artict1'  , 0 , 'Trailers'        , 'None'),
VehicleModel(436 , 'Previon'           , 'previon'  , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(437 , 'Coach'             , 'coach'    , 9 , 'Public Service'  , 'None'),
VehicleModel(438 , 'Cabbie'            , 'cabbie'   , 4 , 'Public Service'  , 'Transfender'),
VehicleModel(439 , 'Stallion'          , 'stallion' , 2 , 'Convertibles'    , 'Transfender'),
VehicleModel(440 , 'Rumpo'             , 'rumpo'    , 4 , 'Industrial'      , 'None'),
VehicleModel(441 , 'RC Bandit'         , 'rcbandit' , 1 , 'RC Vehicles'     , 'None'),
VehicleModel(442 , 'Romero'            , 'romero'   , 2 , 'Unique Vehicles' , 'Transfender'),
VehicleModel(443 , 'Packer'            , 'packer'   , 2 , 'Industrial'      , 'None'),
VehicleModel(444 , 'Monster'           , 'monster'  , 2 , 'Off Road'        , 'None'),
VehicleModel(445 , 'Admiral'           , 'admiral'  , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(446 , 'Squalo'            , 'squalo'   , 1 , 'Boats'           , 'None'),
VehicleModel(447 , 'Seasparrow'        , 'seaspar'  , 2 , 'Helicopters'     , 'None'),
VehicleModel(448 , 'PizzaBoy'          , 'pizzaboy' , 1 , 'Bikes'           , 'None'),
VehicleModel(449 , 'Tram'              , 'tram'     , 2 , 'Unique Vehicles' , 'None'),
VehicleModel(450 , 'Trailer 2'         , 'artict2'  , 0 , 'Trailers'        , 'None'),
VehicleModel(451 , 'Turismo'           , 'turismo'  , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(452 , 'Speeder'           , 'speeder'  , 1 , 'Boats'           , 'None'),
VehicleModel(453 , 'Reefer'            , 'reefer'   , 1 , 'Boats'           , 'None'),
VehicleModel(454 , 'Tropic'            , 'tropic'   , 1 , 'Boats'           , 'None'),
VehicleModel(455 , 'Flatbed'           , 'flatbed'  , 2 , 'Industrial'      , 'None'),
VehicleModel(456 , 'Yankee'            , 'yankee'   , 2 , 'Industrial'      , 'None'),
VehicleModel(457 , 'Caddy'             , 'caddy'    , 2 , 'Unique Vehicles' , 'None'),
VehicleModel(458 , 'Solair'            , 'solair'   , 4 , 'Station Wagons'  , 'Transfender'),
VehicleModel(459 , 'RC Van'            , 'topfun'   , 4 , 'Industrial'      , 'None'),
VehicleModel(460 , 'Skimmer'           , 'skimmer'  , 2 , 'Airplane'        , 'None'),
VehicleModel(461 , 'PCJ-600'           , 'pcj600'   , 2 , 'Bikes'           , 'None'),
VehicleModel(462 , 'Faggio'            , 'faggio'   , 2 , 'Bikes'           , 'None'),
VehicleModel(463 , 'Freeway'           , 'freeway'  , 2 , 'Bikes'           , 'None'),
VehicleModel(464 , 'RC Baron'          , 'rcbaron'  , 2 , 'RC Vehicles'     , 'None'),
VehicleModel(465 , 'RC Raider'         , 'rcraider' , 2 , 'RC Vehicles'     , 'None'),
VehicleModel(466 , 'Glendale'          , 'glendale' , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(467 , 'Oceanic'           , 'oceanic'  , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(468 , 'Sanchez'           , 'sanchez'  , 2 , 'Bikes'           , 'None'),
VehicleModel(469 , 'Sparrow'           , 'sparrow'  , 2 , 'Helicopters'     , 'None'),
VehicleModel(470 , 'Patriot'           , 'patriot'  , 4 , 'Off Road'        , 'None'),
VehicleModel(471 , 'Quad'              , 'quad'     , 2 , 'Bikes'           , 'None'),
VehicleModel(472 , 'Coastguard'        , 'coastg'   , 1 , 'Boats'           , 'None'),
VehicleModel(473 , 'Dinghy'            , 'dinghy'   , 1 , 'Boats'           , 'None'),
VehicleModel(474 , 'Hermes'            , 'hermes'   , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(475 , 'Sabre'             , 'sabre'    , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(476 , 'Rustler'           , 'rustler'  , 1 , 'Airplane'        , 'None'),
VehicleModel(477 , 'ZR-350'            , 'zr350'    , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(478 , 'Walton'            , 'walton'   , 2 , 'Industrial'      , 'Transfender'),
VehicleModel(479 , 'Regina'            , 'regina'   , 4 , 'Station Wagons'  , 'Transfender'),
VehicleModel(480 , 'Comet'             , 'comet'    , 2 , 'Convertibles'    , 'Transfender'),
VehicleModel(481 , 'BMX'               , 'bmx'      , 1 , 'Bikes'           , 'None'),
VehicleModel(482 , 'Burrito'           , 'burrito'  , 4 , 'Industrial'      , 'None'),
VehicleModel(483 , 'Camper'            , 'camper'   , 3 , 'Unique Vehicles' , 'None'),
VehicleModel(484 , 'Marquis'           , 'marquis'  , 1 , 'Boats'           , 'None'),
VehicleModel(485 , 'Baggage'           , 'baggage'  , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(486 , 'Dozer'             , 'dozer'    , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(487 , 'Maverick'          , 'maverick' , 4 , 'Helicopters'     , 'None'),
VehicleModel(488 , 'News Chopper'      , 'vcnmav'   , 2 , 'Helicopters'     , 'None'),
VehicleModel(489 , 'Rancher'           , 'rancher'  , 2 , 'Off Road'        , 'Transfender'),
VehicleModel(490 , 'FBI Rancher'       , 'fbiranch' , 4 , 'Public Service'  , 'None'),
VehicleModel(491 , 'Virgo'             , 'virgo'    , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(492 , 'Greenwood'         , 'greenwoo' , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(493 , 'Jetmax'            , 'jetmax'   , 1 , 'Boats'           , 'None'),
VehicleModel(494 , 'Hotring C'         , 'hotring'  , 2 , 'Sport Vehicles'  , 'None'),
VehicleModel(495 , 'Sandking'          , 'sandking' , 2 , 'Off Road'        , 'None'),
VehicleModel(496 , 'Blista Compact'    , 'blistac'  , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(497 , 'Police Maverick'   , 'polmav'   , 4 , 'Helicopters'     , 'None'),
VehicleModel(498 , 'Boxville'          , 'boxville' , 4 , 'Industrial'      , 'None'),
VehicleModel(499 , 'Benson'            , 'benson'   , 2 , 'Industrial'      , 'None'),
VehicleModel(500 , 'Mesa'              , 'mesa'     , 2 , 'Off Road'        , 'Transfender'),
VehicleModel(501 , 'RC Goblin'         , 'rcgoblin' , 2 , 'RC Vehicles'     , 'None'),
VehicleModel(502 , 'Hotring A'         , 'hotrina'  , 2 , 'Sport Vehicles'  , 'None'),
VehicleModel(503 , 'Hotring B'         , 'hotrinb'  , 2 , 'Sport Vehicles'  , 'None'),
VehicleModel(504 , 'Bloodring Banger'  , 'bloodra'  , 2 , 'Saloons'         , 'None'),
VehicleModel(504 , 'Bloodring Banger'  , 'bloodrb'  , 2 , 'Saloons'         , 'None'),
VehicleModel(505 , 'Rancher Lure'      , 'rnchlure' , 2 , 'Off Road'        , 'None'),
VehicleModel(506 , 'Super GT'          , 'supergt'  , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(507 , 'Elegant'           , 'elegant'  , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(508 , 'Journey'           , 'journey'  , 2 , 'Unique Vehicles' , 'None'),
VehicleModel(509 , 'Bike'              , 'bike'     , 1 , 'Bikes'           , 'None'),
VehicleModel(510 , 'Mountain Bike'     , 'mtbike'   , 1 , 'Bikes'           , 'None'),
VehicleModel(511 , 'Beagle'            , 'beagle'   , 2 , 'Airplane'        , 'None'),
VehicleModel(512 , 'Cropduster'        , 'cropdust' , 1 , 'Airplane'        , 'None'),
VehicleModel(513 , 'Stuntplane'        , 'stunt'    , 1 , 'Airplane'        , 'None'),
VehicleModel(514 , 'Tanker'            , 'petro'    , 2 , 'Industrial'      , 'None'),
VehicleModel(515 , 'RoadTrain'         , 'rdtrain'  , 2 , 'Industrial'      , 'None'),
VehicleModel(516 , 'Nebula'            , 'nebula'   , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(517 , 'Majestic'          , 'majestic' , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(518 , 'Buccaneer'         , 'buccanee' , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(519 , 'Shamal'            , 'shamal'   , 1 , 'Airplane'        , 'None'),
VehicleModel(520 , 'Hydra'             , 'hydra'    , 1 , 'Airplane'        , 'None'),
VehicleModel(521 , 'FCR-900'           , 'fcr900'   , 2 , 'Bikes'           , 'None'),
VehicleModel(522 , 'NRG-500'           , 'nrg500'   , 2 , 'Bikes'           , 'None'),
VehicleModel(523 , 'HPV1000'           , 'copbike'  , 2 , 'Public Service'  , 'None'),
VehicleModel(524 , 'Cement Truck'      , 'cement'   , 2 , 'Industrial'      , 'None'),
VehicleModel(525 , 'Towtruck'          , 'towtruck' , 2 , 'Unique Vehicles' , 'None'),
VehicleModel(526 , 'Fortune'           , 'fortune'  , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(527 , 'Cadrona'           , 'cadrona'  , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(528 , 'FBI Truck'         , 'fbitruck' , 2 , 'Public Service'  , 'None'),
VehicleModel(529 , 'Willard'           , 'willard'  , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(530 , 'Forklift'          , 'forklift' , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(531 , 'Tractor'           , 'tractor'  , 1 , 'Industrial'      , 'None'),
VehicleModel(532 , 'Combine Harvester' , 'combine'  , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(533 , 'Feltzer'           , 'feltzer'  , 2 , 'Convertibles'    , 'Transfender'),
VehicleModel(534 , 'Remington'         , 'remingtn' , 2 , 'Lowriders'       , 'Loco Low Co'),
VehicleModel(535 , 'Slamvan'           , 'slamvan'  , 2 , 'Lowriders'       , 'Loco Low Co'),
VehicleModel(536 , 'Blade'             , 'blade'    , 2 , 'Lowriders'       , 'Loco Low Co'),
VehicleModel(537 , 'Freight'           , 'freight'  , 2 , 'Unique Vehicles' , 'None'),
VehicleModel(538 , 'Brownstreak'       , 'streak'   , 2 , 'Unique Vehicles' , 'None'),
VehicleModel(539 , 'Vortex'            , 'vortex'   , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(540 , 'Vincent'           , 'vincent'  , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(541 , 'Bullet'            , 'bullet'   , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(542 , 'Clover'            , 'clover'   , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(543 , 'Sadler'            , 'sadler'   , 2 , 'Industrial'      , 'None'),
VehicleModel(544 , 'FiretruckLA'       , 'firela'   , 2 , 'Public Service'  , 'None'),
VehicleModel(545 , 'Hustler'           , 'hustler'  , 2 , 'Unique Vehicles' , 'Transfender'),
VehicleModel(546 , 'Intruder'          , 'intruder' , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(547 , 'Primo'             , 'primo'    , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(548 , 'Cargobob'          , 'cargobob' , 2 , 'Helicopters'     , 'None'),
VehicleModel(549 , 'Tampa'             , 'tampa'    , 2 , 'Saloons'         , 'Transfender'),
VehicleModel(550 , 'Sunrise'           , 'sunrise'  , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(551 , 'Merit'             , 'merit'    , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(552 , 'Utility Van'       , 'utility'  , 2 , 'Industrial'      , 'None'),
VehicleModel(553 , 'Nevada'            , 'nevada'   , 1 , 'Airplane'        , 'None'),
VehicleModel(554 , 'Yosemite'          , 'yosemite' , 2 , 'Industrial'      , 'None'),
VehicleModel(555 , 'Windsor'           , 'windsor'  , 2 , 'Convertibles'    , 'Transfender'),
VehicleModel(556 , 'Monster A'         , 'monstera' , 2 , 'Off Road'        , 'None'),
VehicleModel(557 , 'Monster B'         , 'monsterb' , 2 , 'Off Road'        , 'None'),
VehicleModel(558 , 'Uranus'            , 'uranus'   , 2 , 'Sport Vehicles'  , 'Wheel Arch Angels'),
VehicleModel(559 , 'Jester'            , 'jester'   , 2 , 'Sport Vehicles'  , 'Wheel Arch Angels'),
VehicleModel(560 , 'Sultan'            , 'sultan'   , 4 , 'Saloons'         , 'Wheel Arch Angels'),
VehicleModel(561 , 'Stratum'           , 'stratum'  , 4 , 'Station Wagons'  , 'Wheel Arch Angels'),
VehicleModel(562 , 'Elegy'             , 'elegy'    , 2 , 'Saloons'         , 'Wheel Arch Angels'),
VehicleModel(563 , 'Raindance'         , 'raindanc' , 2 , 'Helicopters'     , 'None'),
VehicleModel(564 , 'RC Tiger'          , 'rctiger'  , 1 , 'RC Vehicles'     , 'None'),
VehicleModel(565 , 'Flash'             , 'flash'    , 2 , 'Sport Vehicles'  , 'Wheel Arch Angels'),
VehicleModel(566 , 'Tahoma'            , 'tahoma'   , 4 , 'Lowriders'       , 'Loco Low Co'),
VehicleModel(567 , 'Savanna'           , 'savanna'  , 4 , 'Lowriders'       , 'Loco Low Co'),
VehicleModel(568 , 'Bandito'           , 'bandito'  , 1 , 'Off Road'        , 'None'),
VehicleModel(569 , 'Freight Trailer'   , 'freiflat' , 2 , 'Trailers'        , 'None'),
VehicleModel(570 , 'Streak Trailer'    , 'streakc'  , 6 , 'Trailers'        , 'None'),
VehicleModel(571 , 'Kart'              , 'kart'     , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(572 , 'Mower'             , 'mower'    , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(573 , 'Dune'              , 'duneride' , 2 , 'Off Road'        , 'None'),
VehicleModel(574 , 'Sweeper'           , 'sweeper'  , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(575 , 'Broadway'          , 'broadway' , 2 , 'Lowriders'       , 'Loco Low Co'),
VehicleModel(576 , 'Tornado'           , 'tornado'  , 2 , 'Lowriders'       , 'Loco Low Co'),
VehicleModel(577 , 'AT400'             , 'at400'    , 2 , 'Airplane'        , 'None'),
VehicleModel(578 , 'DFT-30'            , 'dft30'    , 2 , 'Industrial'      , 'None'),
VehicleModel(579 , 'Huntley'           , 'huntley'  , 4 , 'Off Road'        , 'Transfender'),
VehicleModel(580 , 'Stafford'          , 'stafford' , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(581 , 'BF-400'            , 'bf400'    , 2 , 'Bikes'           , 'None'),
VehicleModel(582 , 'Newsvan'           , 'newsvan'  , 4 , 'Industrial'      , 'None'),
VehicleModel(583 , 'Tug'               , 'tug'      , 1 , 'Unique Vehicles' , 'None'),
VehicleModel(584 , 'Petrol Trailer'    , 'petrotr'  , 0 , 'Trailers'        , 'None'),
VehicleModel(585 , 'Emperor'           , 'emperor'  , 4 , 'Saloons'         , 'Transfender'),
VehicleModel(586 , 'Wayfarer'          , 'wayfarer' , 2 , 'Bikes'           , 'None'),
VehicleModel(587 , 'Euros'             , 'euros'    , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(588 , 'Hotdog'            , 'hotdog'   , 2 , 'Unique Vehicles' , 'None'),
VehicleModel(589 , 'Club'              , 'club'     , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(590 , 'Freight Trailer'   , 'freibox'  , 0 , 'Trailers'        , 'None'),
VehicleModel(591 , 'Trailer 3'         , 'artict3'  , 0 , 'Trailers'        , 'None'),
VehicleModel(592 , 'Andromada'         , 'androm'   , 2 , 'Airplane'        , 'None'),
VehicleModel(593 , 'Dodo'              , 'dodo'     , 2 , 'Airplane'        , 'None'),
VehicleModel(594 , 'RC Cam'            , 'rccam'    , 2 , 'RC Vehicles'     , 'None'),
VehicleModel(595 , 'Launch'            , 'launch'   , 1 , 'Boats'           , 'None'),
VehicleModel(596 , 'LSPD car'          , 'copcarla' , 4 , 'Public Service'  , 'None'),
VehicleModel(597 , 'SFPD car'          , 'copcarsf' , 4 , 'Public Service'  , 'None'),
VehicleModel(598 , 'LVPD car'          , 'copcarvg' , 4 , 'Public Service'  , 'None'),
VehicleModel(599 , 'Ranger'            , 'copcarru' , 2 , 'Public Service'  , 'None'),
VehicleModel(600 , 'Picador'           , 'picador'  , 2 , 'Industrial'      , 'Transfender'),
VehicleModel(601 , 'SWAT'              , 'swatvan'  , 2 , 'Public Service'  , 'None'),
VehicleModel(602 , 'Alpha'             , 'alpha'    , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(603 , 'Phoenix'           , 'phoenix'  , 2 , 'Sport Vehicles'  , 'Transfender'),
VehicleModel(604 , 'Glendale damaged'  , 'glenshit' , 4 , 'Saloons'         , 'None'),
VehicleModel(605 , 'Sadler damaged'    , 'sadlshit' , 2 , 'Industrial'      , 'None'),
VehicleModel(606 , 'Baggage Trailer A' , 'bagboxa'  , 0 , 'Trailers'        , 'None'),
VehicleModel(607 , 'Baggage Trailer B' , 'bagboxb'  , 0 , 'Trailers'        , 'None'),
VehicleModel(608 , 'Stairs Trailer'    , 'tugstair' , 0 , 'Trailers'        , 'None'),
VehicleModel(609 , 'Boxville'          , 'boxburg'  , 4 , 'Industrial'      , 'None'),
VehicleModel(610 , 'Farm Trailer'      , 'farmtr1'  , 0 , 'Trailers'        , 'None'),
VehicleModel(611 , 'Utility Trailer'   , 'utiltr1'  , 0 , 'Trailers'        , 'None'),
]

# enum makes code more readable
# e.g. VEHICLE.HYDRA returns hydra model id(520)
VEHICLE = enum.IntEnum('VEHICLE', {m.model.upper():m.model_id for m in vehicle_models if m != None})

class Vehicle(VehicleModel):
    def __init__(self, model_id, id):
        m = vehicle_models[model_id]
        super().__init__(model_id, m.name, m.model, m.seat_count, m.category, m.mod_shop)
        self.id = id
        self.pos = None # vehicle position as Vec3
        self.dir = None # vehicle direction as Quat
        self.health = None
        self.seats = [None] * self.seat_count
